# -*- coding: utf-8 -*-
"""ML11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywF3nH_yeFG00VdK27HtdkJ0ZXe4pyDx
"""

# Credit Score Classification using Machine Learning

import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# --------------------------------------------------
# 1. Load Dataset (Used as Credit Dataset Simulation)
# --------------------------------------------------
data = load_breast_cancer()

X = data.data
y = data.target   # 0 = Bad Credit , 1 = Good Credit (simulated)

# --------------------------------------------------
# 2. Train Test Split
# --------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --------------------------------------------------
# 3. Feature Scaling
# --------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# --------------------------------------------------
# 4. Train Model (Logistic Regression)
# --------------------------------------------------
model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

# --------------------------------------------------
# 5. Predictions
# --------------------------------------------------
y_pred = model.predict(X_test)

# --------------------------------------------------
# 6. Model Evaluation
# --------------------------------------------------
print("Accuracy :", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n", classification_report(y_test, y_pred))

# --------------------------------------------------
# 7. Predict Credit Score for New Customer
# --------------------------------------------------
# Example customer data (random values similar to dataset scale)
new_customer = [14, 20, 90, 600, 0.1, 0.2, 0.15, 0.08, 0.18, 0.06,
                0.4, 1.2, 2.5, 40, 0.006, 0.03, 0.04, 0.01, 0.02, 0.003,
                15, 25, 100, 700, 0.15, 0.25, 0.30, 0.12, 0.28, 0.08]

new_customer = scaler.transform([new_customer])
prediction = model.predict(new_customer)

if prediction[0] == 1:
    print("\nPrediction for new customer: GOOD CREDIT")
else:
    print("\nPrediction for new customer: BAD CREDIT")