# -*- coding: utf-8 -*-
"""ML12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J6_Ky2Q_TRqdEB3X_5oLw27tXyoNJ0E-
"""

# Iris Flower Classification using KNN

import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# --------------------------------------------------
# 1. Load Iris Dataset
# --------------------------------------------------
iris = load_iris()
X = iris.data          # Features (sepal/petal length & width)
y = iris.target        # Classes (0=setosa,1=versicolor,2=virginica)

# --------------------------------------------------
# 2. Split Dataset
# --------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --------------------------------------------------
# 3. Feature Scaling (important for KNN)
# --------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# --------------------------------------------------
# 4. Train KNN Model
# --------------------------------------------------
k = 5
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

# --------------------------------------------------
# 5. Predictions
# --------------------------------------------------
y_pred = knn.predict(X_test)

# --------------------------------------------------
# 6. Model Evaluation
# --------------------------------------------------
print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

print("\nClassification Report:\n", classification_report(y_test, y_pred))

# --------------------------------------------------
# 7. Predict New Flower
# --------------------------------------------------
# Input: [sepal length, sepal width, petal length, petal width]
new_flower = [[5.1, 3.5, 1.4, 0.2]]

new_flower_scaled = scaler.transform(new_flower)
prediction = knn.predict(new_flower_scaled)

flower_names = iris.target_names
print("\nPredicted Flower:", flower_names[prediction][0])