# -*- coding: utf-8 -*-
"""ML13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bpg4zgZM3vYIle7LGfd2ZqQjPNPQSiuk
"""

# Car Price Prediction using Linear Regression

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# --------------------------------------------------
# 1. Create Sample Car Dataset
# --------------------------------------------------
np.random.seed(42)

n = 300
data = pd.DataFrame({
    "Year": np.random.randint(2005, 2023, n),
    "Present_Price": np.random.uniform(4, 20, n),     # in lakhs
    "Kms_Driven": np.random.randint(5000, 100000, n),
    "Fuel_Type": np.random.randint(0, 2, n),          # 0=Petrol,1=Diesel
    "Seller_Type": np.random.randint(0, 2, n),        # 0=Dealer,1=Individual
    "Transmission": np.random.randint(0, 2, n)        # 0=Manual,1=Auto
})

# Create realistic target variable (Car Selling Price)
data["Selling_Price"] = (
    data["Present_Price"] * 0.6
    - (2025 - data["Year"]) * 0.2
    - data["Kms_Driven"] / 100000
    + data["Fuel_Type"] * 1.5
    + data["Transmission"] * 1.0
    + np.random.randn(n)
)

# --------------------------------------------------
# 2. Split Features & Target
# --------------------------------------------------
X = data.drop("Selling_Price", axis=1)
y = data["Selling_Price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# --------------------------------------------------
# 3. Feature Scaling
# --------------------------------------------------
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

# --------------------------------------------------
# 4. Train Linear Regression Model
# --------------------------------------------------
model = LinearRegression()
model.fit(X_train, y_train)

# --------------------------------------------------
# 5. Model Evaluation
# --------------------------------------------------
y_pred = model.predict(X_test)

print("R2 Score:", r2_score(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

# --------------------------------------------------
# 6. Predict Price of New Car
# --------------------------------------------------
# Example car: Year, PresentPrice, Kms, FuelType, SellerType, Transmission
new_car = [[2019, 12.5, 30000, 1, 0, 1]]

new_car_scaled = scaler.transform(new_car)
predicted_price = model.predict(new_car_scaled)

print("\nPredicted Selling Price (in lakhs):", round(predicted_price[0],2))