# -*- coding: utf-8 -*-
"""ml2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOPXlq1riNEknUE1lIvSYqRSGPDnwNho
"""

import pandas as pd

# -------------------------------
# Create dataset inside code
# -------------------------------
data = {
    'Sky': ['Sunny', 'Sunny', 'Rainy', 'Sunny'],
    'AirTemp': ['Warm', 'Warm', 'Cold', 'Warm'],
    'Humidity': ['Normal', 'High', 'High', 'High'],
    'Wind': ['Strong', 'Strong', 'Strong', 'Weak'],
    'Water': ['Warm', 'Warm', 'Warm', 'Warm'],
    'Forecast': ['Same', 'Same', 'Change', 'Same'],
    'PlayTennis': ['Yes', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)
print("Training Data:\n")
print(df)

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

num_attributes = X.shape[1]

# -------------------------------
# Initialize S and G
# -------------------------------
S = ['0'] * num_attributes
G = [['?'] * num_attributes]

# -------------------------------
# Candidate Elimination Algorithm
# -------------------------------
for i in range(len(X)):
    print(f"\nTraining example {i+1}: {X[i]} -> {y[i]}")

    if y[i] == 'Yes':
        G = [g for g in G if all(g[j] == '?' or g[j] == X[i][j] for j in range(num_attributes))]

        for j in range(num_attributes):
            if S[j] == '0':
                S[j] = X[i][j]
            elif S[j] != X[i][j]:
                S[j] = '?'

    else:
        new_G = []
        for g in G:
            if all(g[j] == '?' or g[j] == X[i][j] for j in range(num_attributes)):
                for j in range(num_attributes):
                    if S[j] != '?' and S[j] != X[i][j]:
                        new_hyp = g.copy()
                        new_hyp[j] = S[j]
                        if new_hyp not in new_G:
                            new_G.append(new_hyp)
            else:
                new_G.append(g)
        G = new_G

    print("S boundary:", S)
    print("G boundary:", G)

# -------------------------------
# Final Output
# -------------------------------
print("\nFinal Version Space:")
print("Most Specific Hypothesis (S):", S)
print("Most General Hypotheses (G):")
for g in G:
    print(g)