# -*- coding: utf-8 -*-
"""ml4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srXl4i2BKrFCtvhlVFuvBsU5Fq6Gsdv8
"""

import numpy as np

# -------------------------------
# Step 1: Define activation function
# -------------------------------
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# -------------------------------
# Step 2: Training dataset (XOR)
# -------------------------------
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

y = np.array([[0], [1], [1], [0]])

# -------------------------------
# Step 3: Initialize parameters
# -------------------------------
input_neurons = 2
hidden_neurons = 2
output_neurons = 1

np.random.seed(1)

# Weights and biases
weight_input_hidden = np.random.uniform(size=(input_neurons, hidden_neurons))
bias_hidden = np.random.uniform(size=(1, hidden_neurons))

weight_hidden_output = np.random.uniform(size=(hidden_neurons, output_neurons))
bias_output = np.random.uniform(size=(1, output_neurons))

learning_rate = 0.5
epochs = 10000

# -------------------------------
# Step 4: Training using Backpropagation
# -------------------------------
for epoch in range(epochs):

    # Forward Propagation
    hidden_layer_input = np.dot(X, weight_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)

    output_layer_input = np.dot(hidden_layer_output, weight_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_input)

    # Error calculation
    error = y - predicted_output

    # Backward Propagation
    d_output = error * sigmoid_derivative(predicted_output)
    d_hidden = d_output.dot(weight_hidden_output.T) * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    weight_hidden_output += hidden_layer_output.T.dot(d_output) * learning_rate
    bias_output += np.sum(d_output, axis=0, keepdims=True) * learning_rate

    weight_input_hidden += X.T.dot(d_hidden) * learning_rate
    bias_hidden += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

# -------------------------------
# Step 5: Output after training
# -------------------------------
print("Final predicted output after training:")
print(np.round(predicted_output, 3))

# -------------------------------
# Step 6: Testing with new samples
# -------------------------------
print("\nTesting the trained ANN:")
for i in range(len(X)):
    print(f"Input: {X[i]} -> Output: {np.round(predicted_output[i][0])}")