# -*- coding: utf-8 -*-
"""ML9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iv5vc1Zc2MhYoCeHaaewZvIvIUWq1qew
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# --------------------------------------------------
# 1. Create Non-Linear Dataset
# --------------------------------------------------
np.random.seed(42)
X = np.linspace(-5, 5, 200).reshape(-1,1)
y = 3*X**2 + 2*X + 5 + np.random.randn(200,1)*5

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# --------------------------------------------------
# 2. Linear Regression (from scratch)
# --------------------------------------------------
Xb_train = np.c_[np.ones(X_train.shape[0]), X_train]
Xb_test  = np.c_[np.ones(X_test.shape[0]),  X_test]

def train_linear(X, y, lr=0.01, iters=2000):
    m, n = X.shape
    w = np.zeros((n,1))
    for i in range(iters):
        pred = X @ w
        grad = (1/m) * X.T @ (pred - y)
        w -= lr * grad
    return w

def predict(X, w):
    return X @ w

w_linear = train_linear(Xb_train, y_train)
y_pred_linear = predict(Xb_test, w_linear)

# --------------------------------------------------
# 3. Polynomial Regression (degree 2)
# --------------------------------------------------
X_poly_train = np.c_[np.ones(X_train.shape[0]), X_train, X_train**2]
X_poly_test  = np.c_[np.ones(X_test.shape[0]),  X_test,  X_test**2]

w_poly = train_linear(X_poly_train, y_train)
y_pred_poly = predict(X_poly_test, w_poly)

# --------------------------------------------------
# 4. Metrics
# --------------------------------------------------
def r2_score(y_true, y_pred):
    ss_total = np.sum((y_true - np.mean(y_true))**2)
    ss_res   = np.sum((y_true - y_pred)**2)
    return 1 - (ss_res/ss_total)

def mse(y_true, y_pred):
    return np.mean((y_true - y_pred)**2)

print("\n---- MODEL COMPARISON ----")
print("Linear Regression:")
print("MSE =", mse(y_test, y_pred_linear))
print("R2  =", r2_score(y_test, y_pred_linear))

print("\nPolynomial Regression:")
print("MSE =", mse(y_test, y_pred_poly))
print("R2  =", r2_score(y_test, y_pred_poly))

# --------------------------------------------------
# 5. Visualization (FIXED PART)
# --------------------------------------------------
plt.scatter(X, y, label="Actual Data")

# SORT VALUES CORRECTLY ✅
sorted_idx = np.argsort(X[:,0])
X_sorted = X[sorted_idx]   # <-- Correct line

# Linear fit line
plt.plot(
    X_sorted,
    predict(np.c_[np.ones(len(X_sorted)), X_sorted], w_linear),
    label="Linear Fit"
)

# Polynomial fit curve
plt.plot(
    X_sorted,
    predict(np.c_[np.ones(len(X_sorted)), X_sorted, X_sorted**2], w_poly),
    label="Polynomial Fit"
)

plt.legend()
plt.title("Linear vs Polynomial Regression")
plt.show()